# Generated by Django 5.1.6 on 2025-02-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DRESS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], default='M', max_length=4)),
                ('color', models.CharField(choices=[('RED', 'Red'), ('BLU', 'Blue'), ('GRN', 'Green'), ('BLK', 'Black'), ('WHT', 'White'), ('YLW', 'Yellow'), ('ORG', 'Orange'), ('PNK', 'Pink'), ('PRP', 'Purple'), ('BRN', 'Brown'), ('GRY', 'Gray'), ('NVY', 'Navy'), ('TUR', 'Turquoise'), ('GLD', 'Gold'), ('SLV', 'Silver')], default='Red', max_length=3)),
                ('price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('image', models.ImageField(upload_to='product_img/')),
                ('description', models.TextField()),
            ],
        ),
    ]
